### ISSUE TITLE
Clicking on people without a city in their profile does strange things

### ISSUE THREAD

**Issue by kewisch** [MozillaDE/MozMap#1]
Find me in MozMap, I only have "Germany" mentioned. Clicking on me reloads the map and resets it to somewhere different.

**Comment by freaktechnik** [comment]
I just noticed the same thing.

**Comment by alex-pl** [comment]
I did an update on the server a few minutes ago and forgot to test the my last small commit locally.
It should be fixed already ;).

**Comment by alex-pl** [comment]
Is the issue still present if you (force-)reload the page?

**Comment by freaktechnik** [comment]
Fixed for me.
